### ISSUE TITLE
Rimozione modalità ingresso IT

### ISSUE THREAD

**Issue by astagi** [solari-sviluppo-prodotti/sol-verificaC19-sdk-cpp-linux#8]
Rimuovere e adeguarsi all'ultima versione del SDK ufficiale rimuovendo la modalità di ingresso IT. [CHANGELOG](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/blob/main/CHANGELOG.md#1110---13062022)

**Comment by solari-sviluppo-prodotti** [comment]
Rimossa nella versione 1.1.11
