### ISSUE TITLE
Aggiornamento core per allineamento a release DGC-SDK Android/Kotlin 1.1.11

### ISSUE THREAD

**Issue by astagi** [solari-sviluppo-prodotti/sol-verificaC19-sdk-cpp-linux#9]
Buonasera,

si prega di procedere all'aggiornamento del core di questo SDK per allineamento a release DGC-SDK Android/Kotlin 1.1.11.

- Rimozione delle modalità di verifica RSA (booster) e Rafforzata (2G)

- Aggiornamento del flusso di validazione con solo i controlli previsti per la modalità di verifica Base (3G)

Maggiori dettagli: https://github.com/ministero-salute/it-dgc-documentation/pull/29

cc @solari-sviluppo-prodotti

**Comment by solari-sviluppo-prodotti** [comment]
Rilasciata la versione 1.1.12 allienata alla release DGC-SDK Android/Kotlin 1.1.11
